#!/usr/bin/env python3
"""Regenerate the WMMA GEMM selection tables and kernel instantiation units.

    python3 rocm_tools/gen_wmma_gemm_table.py            # rewrite the generated files
    python3 rocm_tools/gen_wmma_gemm_table.py --check    # exit 1 if they are stale
    python3 rocm_tools/gen_wmma_gemm_table.py --tune     # tuning build: every config compiled
                                                         # for every table arch (then rebuild,
                                                         # run rocm_tools/tune_wmma_gemm.py,
                                                         # and regenerate without --tune)

Inputs, per table arch:
  1. rocm_wmma_gemm's tuned configs, vendored at
     exllamav3/exllamav3_ext/rocm/vendor/rocm_wmma_gemm/config/gemm_config_<arch>_f32.json.
     Float-accumulator tables only: hgemm accumulates in fp32 for fp32 AND fp16 output, so
     the library's 16-bit-accumulator tables do not apply. Only layout A=row, B=row, C=row
     is kept (hgemm's only layout). All of its entries have M, N >= 1024.
  2. Optional local measurements, exllamav3/exllamav3_ext/rocm/wmma_gemm_tuned_<arch>.json,
     written by rocm_tools/tune_wmma_gemm.py on that GPU. They cover the small-M / narrow-N
     prefill shapes the library table does not (where its big tiles leave most of the GPU
     idle) and record, per shape, whether WMMA beat hipBLAS for fp32 and for fp16 output.
     A local entry replaces a library entry with the same (M, N, K).

Each table entry carries route flags (1 = fp32 output, 2 = fp16 output): the backend runs a
call only if the selected entry's flag for its output dtype is set. Library-only entries
(no hipBLAS comparison was measured) get fp32 only. A table with no local measurements is
marked untuned, and the backend then also requires m >= UNTUNED_MIN_M, keeping it near the
library's tuned domain (M >= 1024) instead of extrapolating big tiles down to small grids.

Output (exllamav3/exllamav3_ext/rocm/):
  wmma_gemm_table_rdna.hip.h       unique configs (arch bitmask of the tables that use them)
                                   and one (M, N, K) -> config table per arch
  wmma_gemm_inst<i>_rdna.hip       launchers, configs split round-robin over UNITS files so
                                   setup.py's parallel build compiles them concurrently

Arch bits must agree with EXL3_WMMA_ARCH_* in rocm/wmma_gemm_rdna.hip.h. gfx1101 runs the
gfx1100 table (same WGP design, fewer CUs; nothing here depends on the CU count).
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROCM = os.path.join(os.path.dirname(HERE), "exllamav3", "exllamav3_ext", "rocm")
CONFIG_DIR = os.path.join(ROCM, "vendor", "rocm_wmma_gemm", "config")

# (table name, arch bit)
ARCHES = [("gfx1151", 1), ("gfx1100", 2)]
ALL_BITS = 3
UNITS = 4
UNTUNED_MIN_M = 512
ROUTE_FP32, ROUTE_FP16 = 1, 2
RRR = {"A": "row_major", "B": "row_major", "C": "row_major"}
KEYS = ("warps_m", "warps_n", "warp_tile_m", "warp_tile_n", "k_slices", "single_buffer", "swizzle", "bits")


def cfg_tuple(c):
    return tuple(int(c[k]) for k in KEYS)


def library_entries(arch):
    with open(os.path.join(CONFIG_DIR, f"gemm_config_{arch}_f32.json")) as f:
        confs = json.load(f)["configurations"]
    out = {}
    for c in confs:
        if {k: c["layout"].get(k) for k in "ABC"} != RRR:
            continue
        r = c["range"]
        out[(r["M"], r["N"], r["K"])] = (cfg_tuple(c["config"]), ROUTE_FP32)
    return out


def local_entries(arch):
    path = os.path.join(ROCM, f"wmma_gemm_tuned_{arch}.json")
    if not os.path.exists(path):
        return None
    with open(path) as f:
        confs = json.load(f)["configurations"]
    out = {}
    for c in confs:
        r = c["range"]
        route = (ROUTE_FP32 if c["route"]["fp32"] else 0) | (ROUTE_FP16 if c["route"]["fp16"] else 0)
        out[(r["M"], r["N"], r["K"])] = (cfg_tuple(c["config"]), route)
    return out


def generate(tune):
    tables, tuned = {}, {}
    masks = {}
    for name, bit in ARCHES:
        ent = library_entries(name)
        loc = local_entries(name)
        tuned[name] = loc is not None
        if loc:
            ent.update(loc)
        tables[name] = ent
        for cfg, _ in ent.values():
            masks[cfg] = masks.get(cfg, 0) | bit
    if tune:
        masks = {c: ALL_BITS for c in masks}
    cfgs = sorted(masks)
    idx = {c: i for i, c in enumerate(cfgs)}

    hdr = [
        "// Auto-generated by rocm_tools/gen_wmma_gemm_table.py -- DO NOT EDIT" + ("  [TUNING BUILD]" if tune else ""),
        "// Sources: rocm/vendor/rocm_wmma_gemm/config/gemm_config_<arch>_f32.json (rocm_wmma_gemm",
        "// ea3aa74, MIT, Copyright (c) 2024 Adel Johar; layout A=row B=row C=row only) and the local",
        "// measurements in rocm/wmma_gemm_tuned_<arch>.json (rocm_tools/tune_wmma_gemm.py).",
        "#pragma once",
        '#include "wmma_gemm_rdna.hip.h"',
        "",
    ]
    for i, c in enumerate(cfgs):
        hdr.append(f"void exl3_wmma_launch_c{i}(void*, const half*, const half*, int, int, int, bool, bool, hipStream_t);")
    hdr += ["", "// warps_m, warps_n, warp_tile_m, warp_tile_n, k_slices, single_buffer, swizzle, bits, arch_mask, launcher",
            f"static const Exl3WmmaCfg exl3_wmma_cfgs[{len(cfgs)}] =", "{"]
    for i, c in enumerate(cfgs):
        hdr.append("    { " + ", ".join(str(v) for v in c) + f", {masks[c]}, exl3_wmma_launch_c{i} }},")
    hdr += ["};", ""]
    for name, _ in ARCHES:
        ent = sorted(tables[name].items())
        src = "library + local measurements" if tuned[name] else "library only (untuned here)"
        hdr += [f"// {name}: {len(ent)} shapes, {src}. M, N, K, config, route (1 = fp32 out, 2 = fp16 out)",
                f"static const Exl3WmmaEntry exl3_wmma_entries_{name}[{len(ent)}] =", "{"]
        for (m, n, k), (c, route) in ent:
            hdr.append(f"    {{ {m}, {n}, {k}, {idx[c]}, {route} }},")
        hdr += ["};", ""]
    hdr += ["// arch bit, entries, count, min m (untuned tables stay near the library's M >= 1024 domain)",
            "static const Exl3WmmaTable exl3_wmma_tables[] =", "{"]
    for name, bit in ARCHES:
        hdr.append(f"    {{ {bit}, exl3_wmma_entries_{name}, {len(tables[name])}, {0 if tuned[name] else UNTUNED_MIN_M} }},  // {name}")
    hdr += ["};", ""]
    files = {os.path.join(ROCM, "wmma_gemm_table_rdna.hip.h"): "\n".join(hdr)}

    for u in range(UNITS):
        body = [
            "// Auto-generated by rocm_tools/gen_wmma_gemm_table.py -- DO NOT EDIT",
            f"// WMMA GEMM launchers, unit {u} of {UNITS} (configs i with i % {UNITS} == {u})",
            "#define EXL3_WMMA_INSTANTIATE",
            '#include "wmma_gemm_rdna.hip.h"',
            "",
        ]
        for i, c in enumerate(cfgs):
            if i % UNITS == u:
                body.append(f"EXL3_WMMA_LAUNCHER(exl3_wmma_launch_c{i}, " + ", ".join(str(v) for v in c) + f", {masks[c]})")
        body.append("")
        files[os.path.join(ROCM, f"wmma_gemm_inst{u}_rdna.hip")] = "\n".join(body)
    return files


def main():
    ap = argparse.ArgumentParser(description = __doc__, formatter_class = argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action = "store_true", help = "only verify the generated files are current")
    ap.add_argument("--tune", action = "store_true", help = "compile every config for every table arch")
    args = ap.parse_args()
    files = generate(args.tune)
    stale = []
    for path, text in files.items():
        cur = open(path).read() if os.path.exists(path) else None
        if cur != text:
            stale.append(path)
            if not args.check:
                with open(path, "w") as f:
                    f.write(text)
    for p in stale:
        print(("stale: " if args.check else "wrote: ") + os.path.relpath(p, os.path.dirname(HERE)))
    if not stale:
        print("up to date")
    return 1 if (args.check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
