#!/usr/bin/env python3
"""Regenerate the two v1.5.3 "deterministic int8" siblings from their upstream sources.

    python rocm_tools/gen_det_siblings.py          # writes rocm/routing_gemm_rdna.hip, rocm/hc_mix_tiled_rdna.hip
    python rocm_tools/gen_det_siblings.py --check  # exit 1 if the checked-in siblings differ

Upstream v1.5.3 added routing_gemm.cu (int8 Ozaki-style router projection) and hc_mix_tiled.cu
(tiled GatedResidual prefill mix), both built on det_gemm.cuh's mma.m16n8k32.s8 / cp.async /
ldmatrix PTX. They exist so tensor-parallel ranks of different NVIDIA architectures agree bit for
bit; on ROCm there is no TP and no int8 PTX, and hip_compat's device-pass __CUDA_ARCH__ (1)
compiles every PTX helper in det_gemm.cuh out -- so the upstream files BUILD on ROCm but their
GEMM kernels would compute nothing. routing_gemm_det_fits() gates the router path on
compute-capability major >= 8, which HIP reports as 11 on gfx1151: compiled as-is, every
multi-row router call would run the empty kernel and route on garbage.

Each sibling is the upstream file verbatim (include paths one level up) plus anchored edits
asserting their anchors match exactly once, so an upstream move fails loudly:

  routing_gemm_rdna.hip  routing_gemm_det_fits() returns false on ROCm (callers fall back to the
                         RDNA router GEMV at m <= 8 and hgemm above, as before v1.5.3);
                         routing_gemm_det_() / routing_gemm_det() raise if reached anyway.
                         det_quant_weight() and det_math_test() are untouched: plain CUDA, used
                         by block_sparse_mlp_routing._gate_t on every router and by the tests.
  hc_mix_tiled_rdna.hip  gr_mix_tiled() raises. hyperconnections.GatedResidual never selects the
                         tiled path under torch.version.hip (upstream's own guard); prefill mixes
                         take the cuBLAS path (rocm_py EXL3_ROCM_GR_PREFILL fuses its tail).

setup.py ROCM_EXCLUDE and rocm_tools/hipcc_probe.sh exclude the upstream files.
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
EXT = os.path.join(REPO, "exllamav3", "exllamav3_ext")


def upstream(name):
    with open(os.path.join(EXT, name)) as f:
        return f.read()


def rep(s, old, new, count=1):
    n = s.count(old)
    if n != count:
        raise SystemExit(f"anchor matched {n} times (expected {count}):\n{old}")
    return s.replace(old, new)


def includes(s):
    for h in ('"routing.cuh"', '"hc_mix.cuh"', '"util.h"', '"util.cuh"', '"det_gemm.cuh"'):
        s = s.replace(f"#include {h}", f"#include \"../{h[1:]}")
    return s


def header(src, what):
    return (
        "// =============================================================================\n"
        f"// {src} for RDNA -- GENERATED by rocm_tools/gen_det_siblings.py, do not edit\n"
        "// =============================================================================\n"
        "//\n"
        f"// {what}\n"
        "// See the generator's docstring for why; diff against the upstream file to audit.\n"
        "// =============================================================================\n\n"
    )


def gen_routing_gemm():
    s = includes(upstream("routing_gemm.cu"))
    s = rep(s,
        "    if (cc_major < 8) return false;\n",
        "    if (cc_major < 8) return false;\n"
        "#ifdef USE_ROCM\n"
        "    // RDNA sibling: det_gemm.cuh's int8 MMA / cp.async PTX is compiled out on ROCm, so the\n"
        "    // kernels below would compute nothing. Decline: routing_gemv falls back to its non-det path.\n"
        "    return false;\n"
        "#endif\n")
    s = rep(s,
        "void routing_gemm_det_(const at::Tensor& hidden, const at::Tensor& gate_i8, const at::Tensor& gate_sb, at::Tensor& scores, cudaStream_t stream)\n{\n",
        "void routing_gemm_det_(const at::Tensor& hidden, const at::Tensor& gate_i8, const at::Tensor& gate_sb, at::Tensor& scores, cudaStream_t stream)\n{\n"
        "#ifdef USE_ROCM\n"
        "    TORCH_CHECK(false, \"routing_gemm_det: the deterministic int8 router GEMM needs sm_80 PTX and is not available on ROCm\");\n"
        "#endif\n")
    return header("routing_gemm.cu", "routing_gemm_det_fits() -> false and routing_gemm_det_() raises on ROCm.") + s


def gen_hc_mix_tiled():
    s = includes(upstream("hc_mix_tiled.cu"))
    s = rep(s,
        "    at::Tensor mixed                     // (R, D) half out\n)\n{\n",
        "    at::Tensor mixed                     // (R, D) half out\n)\n{\n"
        "#ifdef USE_ROCM\n"
        "    TORCH_CHECK(false, \"gr_mix_tiled: the tiled int8 GatedResidual mix needs sm_80 PTX and is not available on ROCm \"\n"
        "                \"(GatedResidual takes the cuBLAS path there)\");\n"
        "#endif\n")
    return header("hc_mix_tiled.cu", "gr_mix_tiled() raises on ROCm (Python never selects it there).") + s


def main():
    check = "--check" in sys.argv
    out = {
        os.path.join(EXT, "rocm", "routing_gemm_rdna.hip"): gen_routing_gemm(),
        os.path.join(EXT, "rocm", "hc_mix_tiled_rdna.hip"): gen_hc_mix_tiled(),
    }
    bad = 0
    for path, text in out.items():
        if check:
            try:
                cur = open(path).read()
            except FileNotFoundError:
                cur = None
            if cur != text:
                print(f"STALE {os.path.relpath(path, REPO)}")
                bad = 1
            else:
                print(f"ok    {os.path.relpath(path, REPO)}")
        else:
            with open(path, "w") as f:
                f.write(text)
            print(f"wrote {os.path.relpath(path, REPO)}")
    sys.exit(bad)


if __name__ == "__main__":
    main()
